### ISSUE TITLE
el7 packages missing mirror-lists

### ISSUE THREAD

**Issue by Fale** [davidhrbac/mirrorlist#1]
Hi,
el7 package comes with:
- mirrorlist = http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
- mirrorlist = http://mirrorlist.repoforge.org/el7/mirrors-rpmforge-extras
- mirrorlist = http://mirrorlist.repoforge.org/el7/mirrors-rpmforge-testing

as mirrorlists. These mirrorlists are not existing. Would be possible to add those files? (I've noticed that these files are present in the repo (http://apt.sw.be/redhat/el7/en/) so it should be enough to copy them in the appropriate folder :).

Thanks,
Fabio

**Comment by davidhrbac** [comment]
enabled in https://github.com/repoforge/mirror-status/commit/e0798e3c15dcba579f1df88d0a881a4a078b4474

**Comment by Fale** [comment]
still not working :(

**Comment by ghost** [comment]
still not working ...

**Comment by davidhrbac** [comment]
Fixed now.
